<a href="https://colab.research.google.com/github/temalkin/pyTorch-learning/blob/main/Lists_NArrays_Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
import numpy as np
import torch

# LISTS

In [2]:
my_list = [[1,2,3,4,5], [6,7,8,9,10]]
my_list

[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]

# NUMPY ARRAYS

In [6]:
np1 = np.random.rand(3,4)
np1

array([[0.1119968 , 0.04847644, 0.53640513, 0.20215656],
       [0.64827912, 0.10026899, 0.15851069, 0.22799591],
       [0.43853734, 0.04201261, 0.80250732, 0.94308717]])

In [7]:
np1.dtype

dtype('float64')

# TENSORS

In [15]:
tensor_2d = torch.randn(3,4)
tensor_2d
#tensor_2d.dtype

tensor([[ 0.6331, -0.4860,  1.1540, -0.5410],
        [ 1.0679,  0.3906,  1.3443,  0.0986],
        [-0.6668,  0.0629, -0.7039, -0.3572]])

In [12]:
tensor_3d = torch.zeros(2,3,4)
tensor_3d

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [13]:
## Create tensor out of numpy array
my_tensor = torch.tensor(np1)
my_tensor

tensor([[0.1120, 0.0485, 0.5364, 0.2022],
        [0.6483, 0.1003, 0.1585, 0.2280],
        [0.4385, 0.0420, 0.8025, 0.9431]], dtype=torch.float64)