<a href="https://colab.research.google.com/github/temalkin/pyTorch-learning/blob/main/tensor_math.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [25]:
import torch
import numpy as np

In [27]:
tensor_a = torch.tensor([1,2,3,4])
tensor_b = torch.tensor([5,6,7,8])

In [28]:
# Addition
tensor_a + tensor_b

tensor([ 6,  8, 10, 12])

In [29]:
# Addition Longhand
torch.add(tensor_a, tensor_b)

tensor([ 6,  8, 10, 12])

In [30]:
# Subtraction
tensor_b - tensor_a

tensor([4, 4, 4, 4])

In [31]:
# Sub functioan
torch.sub(tensor_b, tensor_a)

tensor([4, 4, 4, 4])

In [32]:
# Multiplication
tensor_a * tensor_b

tensor([ 5, 12, 21, 32])

In [33]:
# F
torch.mul(tensor_a, tensor_b)

tensor([ 5, 12, 21, 32])

In [34]:
# Division
tensor_b / tensor_a

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [35]:
# F
torch.div(tensor_b, tensor_a)

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [36]:
# Remainder Modulus
tensor_b % tensor_a

tensor([0, 0, 1, 0])

In [37]:
# F
torch.remainder(tensor_b, tensor_a)

tensor([0, 0, 1, 0])

In [38]:
# Exponents / power
tensor_a ** tensor_b

tensor([    1,    64,  2187, 65536])

In [40]:
# f
torch.pow(tensor_a, tensor_b)

tensor([    1,    64,  2187, 65536])

In [43]:
# Another way
tensor_a.add(tensor_b)
tensor_b.sub(tensor_a)
tensor_a.mul(tensor_b)

tensor([ 5, 12, 21, 32])

In [44]:
# Reassignment
tensor_a + tensor_b

tensor([ 6,  8, 10, 12])

In [45]:
tensor_a

tensor([1, 2, 3, 4])

In [46]:
# tensor_a = tensor_a + tensor_b
tensor_a.add_(tensor_b)

tensor([ 6,  8, 10, 12])

In [47]:
tensor_a

tensor([ 6,  8, 10, 12])